### ISSUE TITLE
Minimal launch example

### ISSUE THREAD

**Issue by caneta** [gridonic/postcss-replace#3]
Hi and thank you for your plugin.
Could you please give a little snippet as an example?
I would like to do a very simple thing: put my package.json version number in my main.css file.
I run postcss as an npm command:
```
"scripts": {
  ...
  "postcss": "postcss --use autoprefixer --use cssnano -c postcss.json --use postcss-replace /version/1.2.3 -o dist/css/main.css src/css/main.css
  ...
}
```
In my main.css I have `{{ version }}`, but after processing nothing happens...how to run it?
Thank you.

**Comment by mzdr** [comment]
Hi @caneta!

Correct me if I'm wrong, but it seems like that you are using [postcss-cli-simple](https://github.com/pirxpilot/postcss-cli) for your npm script, is that right?

If that’s the case then the way you are passing the data is wrong. Try this:
```
"scripts": {
  "postcss": "postcss --use autoprefixer --use cssnano -c postcss.json --use postcss-replace --postcss-replace.data.version=1.2.3 -o dist/css/main.css src/css/main.css
}
```

You can use the [yargs dot notation](https://www.npmjs.com/package/yargs#dot-notation) for passing complex data like [objects](https://github.com/yargs/yargs/blob/HEAD/docs/tricks.md#objects) via the CLI.

Nevertheless this approach is quite static as your version number is not automatically picked from the `package.json`. I would recommend a slightly different setup: Go with the official [postcss-cli](https://github.com/postcss/postcss-cli) and use a [`postcss.config.js`](https://github.com/gridonic/sass/blob/develop/postcss.config.js). Your [npm script](https://github.com/gridonic/sass/blob/develop/package.json#L18) will look much much smaller and is easier to maintain.

Hope this helps. Happy coding!

**Comment by caneta** [comment]
Hey @mzdr , great advice!
So, I'm trying to refactor my build scripts and now here's my situation:
**package.json**
```
  ...
  "build-css": "npm run build-sass && postcss --use autoprefixer --use cssnano --use postcss-replace -c postcss.config.js -o dist/css/main.css src/scss/main.css"
  ...
```
**postcss.config.js**
```
const pkg = require('./package.json');

module.exports = (ctx) => ({
  plugins: {
    'autoprefixer': {
      'browsers': [
        'ie >= 9',
        'Firefox >= 38',
        'Chrome >= 44',
        'ChromeAndroid >= 44',
        'Safari >= 8',
        'Edge >= 0',
        'iOS >= 8'
      ]
    },
    'cssnano': {
      zindex: false
    },
    'postcss-replace': {
      data: pkg,
      commentsOnly: true
    }
  }
});
```
**main.css**
```
/*! v{{ version }} */
/* ...veeery long CSS... */
```
But my main.css file is still the same at the end of the process...what am I missing?

**Comment by mzdr** [comment]
Hey @caneta,

you’re very close! Try removing `-u autoprefixer -u cssnano -u postcss-replace` from the npm command as this is redundant and possibly overwrites your settings you specify in the `postcss.config.js`.

**Comment by caneta** [comment]
No, I've already tried it but removing that flags, no plugin is applied...

**Comment by mzdr** [comment]
That’s strange. I’m running the identical `postcss.config.js` you have posted above, my test `package.json` `devDependencies` look like this:

```json
"devDependencies": {
    "autoprefixer": "^7.1.6",
    "cssnano": "^3.10.0",
    "postcss-cli": "^4.1.1",
    "postcss-replace": "^1.0.0"
  }
```

My `input.css` looks like that:

```css
/*! {{ version }} */
.a {
    transform: rotate(90deg);
}
```

And my `scripts` look like that:

```json
"scripts": {
    "postcss": "postcss -c postcss.config.js -o index.out.css index.css"
  }
```

And my output css looks like that:

```css
/*! 1.0.0 */.a{-webkit-transform:rotate(90deg);-ms-transform:rotate(90deg);transform:rotate(90deg)}
```

Are you sure that you didn’t forget anything?

**Comment by caneta** [comment]
Ok, it works!
My problem was very simple: old version of postcss-cli, I had a very old 2.6.0...updating it did the trick.
Thank you so much!

**Comment by mzdr** [comment]
Awesome!

Thanks for your feedback. If you have any troubles don’t hesitate to get in touch with us.
