### ISSUE TITLE
Can't replace non-word characters

### ISSUE THREAD

**Issue by doplumi** [gridonic/postcss-replace#36]
Minimal reproduction: https://stackblitz.com/edit/typescript-unaxav?file=replace.ts

It appears that the replace function isn't triggered, so the problem is not in the `data` field.

**Comment by doplumi** [comment]
In my use case, it happens because `Rule`s aren't taken into account.

Adding:
``` 
case 'Rule':
  node.selector = node.selector.replace(regex, replacement);
  break;
```
fixes it.

@mzdr, @dschenk : If this is outside the scope of the package, I'll create a fork, otherwise I'll be happy to provide a PR with additional test cases.

**Comment by dschenk** [comment]
Hi @doplumi

I think it makes sense to include non-word characters as well for replacement. If you can provide a PR I will merge it.

Thanks for opening this issue and providing insights and a possible solution. Much appreciated!
