### ISSUE TITLE
May The `data` Object Value be Empty?

### ISSUE THREAD

**Issue by wesleyboar** [gridonic/postcss-replace#4]
### Unsupported Feature / Missing Caveat Documentation

If a string value in a key/value pair is empty, then replacement does **not** take place.
If that same string value is **not** empty, then replacement does take place.

### Suggestions

- Support feature
- Document caveat

### No Replacement

**`postcss.config.json`**
```javascript
    …
    // Support find and replace
    require('postcss-replace')({
      pattern: '{{\\s?([^\\s]+?)\\s?}}',
      data: {
        'test_color': '' /* ← DIFFERENCE */
      }
    }),
    …
```

**`some-parsed-file.css`**
```css
.test-replace {
  /* Comment test of `{{ test_color }}` */ /* ← DIFFERENCE */
  color: "{{ test_color }}"; /* ← DIFFERENCE */
}
```

### Successful Replacement

**`postcss.config.json`**
```javascript
    …
    // Support find and replace
    require('postcss-replace')({
      pattern: '{{\\s?([^\\s]+?)\\s?}}',
      data: {
        'test_color': 'green' /* ← DIFFERENCE */
      }
    }),
    …
```

**`some-parsed-file.css`**
```css
.test-replace {
  /* Comment test of `green` */ /* ← DIFFERENCE */
  color: "green"; /* ← DIFFERENCE */
}
```

### Use Case

My use case is that my project:

1. Uses [kss-node](https://github.com/kss-node/kss-node) for documentation, and the documentation format may have comments that have a `{{ modifier_class }}` syntax
2. A stylesheet may inadvertently gets parsed by [Twig](https://twig.symfony.com/) when the file content is rendered into a `<style>` tag on a [Twig markdown template](https://twig.symfony.com/doc/2.x/templates.html#synopsis), in which `{{ anything }}` has a special meaning—my goal is to replace the `{{ modifier_class }}` with and empty string.

### Workarounds

- Replace `{{ modifier_class }}` with `__removed_variable__`.
    - This is acceptable.
- Remove comments from CSS.
    - Not ideal, because project is designed to have comments in **non** production CSS.

**Comment by mzdr** [comment]
Hey @wesleyboar!

Thanks a lot for reporting this issue. ❤️  I think this is actually a bug. 👇 

https://github.com/gridonic/postcss-replace/blob/a5d2970612af97566bbd1338f1645b272c1c839b/index.js#L30

Because the value is considered to be `falsy` it will return the original placeholder. I will fix that now. 👍
